FROM docker:24.0

# Install curl, bash
RUN apk add --no-cache bash curl

# Install kubectl in a clean way using hard-coded version
ENV KUBECTL_VERSION=v1.30.1

RUN curl -LO https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    rm kubectl

CMD ["sleep", "3600"]
