apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: jenkins
spec:
  selector:
    app: myapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
