apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: jenkins
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # ✅ FIXED to match container port
  type: ClusterIP
